version: '3.4'
networks:
  frontend:
  backend:
services:
  eventcatalog:
    image: event/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7810
      DatabaseServer: mssqlserver
      DatabaseName: EventDB
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7810:80"
    depends_on:
      - mssqlserver
    networks:
      - frontend
      - backend
    container_name: EventProductserver
  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      EventUrl: http://localhost:7810
    ports:
      - "7811:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - eventcatalog
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1433"
    container_name: mssqlserver
    networks:
      - backend